#!/bin/bash
if [ -z $1 ]; then
    echo 'ERROR: You must provide the secrets name'
    exit 1
fi

path=$(readlink -f "$0")
dir=$(dirname "$path")
kubectl get secrets $1 -o=json | python $dir/secrets.py
